"""Named places and the guided flights for the Knoxville folio sheet.

Coordinates and summit elevations come from GNIS — the 2021 archive file,
the last release that still carried elevations.  Every summit below was
hunted against the Terrarium model within 600 m of its GNIS point and
agrees with its published feet to within 20 m; anything that missed
by more than 130 m was dropped.  Label points for the rivers are placed on
the drawn water inside the block, not at the GNIS mouth.  Tour keys are
(lat, lon, distance km, camera bearing, camera elevation angle).
"""
NOTABLE_GAPS = {   # kept first when the gap layer is thinned by cell
    "Ekaneetlee Gap", "Chilhowee Gap", "Indian Grave Gap", "Tali Gap",
    "Big Medicine Gap", "Double Spring Gap", "Wear Cove Gap", "Sams Gap",
    "Rich Mountain Gap", "Schoolhouse Gap", "Sugartree Gap", "Mineral Gap",
    "Birch Spring Gap", "Fighting Creek Gap", "Huskey Gap", "Haw Gap",
    "Spicy Gap", "Buckeye Gap", "Starkey Gap", "Gold Mine Gap",
}

PEAKS = [  # name, lat, lon, feet, country — coordinates and feet from GNIS
    ("Mount Buckley", 35.5620, -83.5063, 6555, "Smoky Mountains crest"),
    ("Silers Bald", 35.5660, -83.5655, 5607, "Smoky Mountains crest"),
    ("Thunderhead Mountain", 35.5686, -83.7063, 5525, "Smoky Mountains crest"),
    ("Rocky Top", 35.5641, -83.7139, 5440, "Smoky Mountains crest"),
    ("Blockhouse Mountain", 35.5498, -83.7107, 5413, "Smoky Mountains, N.C."),
    ("Cold Spring Knob", 35.5802, -83.6085, 5226, "Smoky Mountains crest"),
    ("Spence Field", 35.5636, -83.7328, 4951, "Smoky Mountains crest"),
    ("Gregory Bald", 35.5207, -83.8655, 4951, "Smoky Mountains crest"),
    ("Doe Knob", 35.5259, -83.8199, 4531, "Smoky Mountains crest"),
    ("Blanket Mountain", 35.6260, -83.6116, 4606, "Smoky Mountains spurs"),
    ("Cove Mountain", 35.6967, -83.6098, 4078, "Smoky Mountains spurs"),
    ("Meigs Mountain", 35.6364, -83.6232, 4016, "Smoky Mountains spurs"),
    ("Rich Mountain", 35.6287, -83.7852, 3694, "Cades Cove rim"),
    ("Cades Cove Mountain", 35.6218, -83.8029, 3376, "Cades Cove rim"),
    ("Look Rock", 35.6334, -83.9415, 2651, "Chilhowee Mountain"),
    ("Chestnut Top", 35.6490, -83.7409, 2408, "Chilhowee Mountain"),
]
CITIES = [  # name, lat, lon, tier (0 = major)
    ("Knoxville", 35.9606, -83.9207, 0),
    ("Maryville", 35.7565, -83.9705, 1),
    ("Sevierville", 35.8681, -83.5618, 1),
    ("Alcoa", 35.7895, -83.9738, 1),
    ("Pigeon Forge", 35.7884, -83.5543, 2),
    ("Gatlinburg", 35.7143, -83.5102, 2),
    ("Townsend", 35.6754, -83.7557, 2),
    ("Walland", 35.7281, -83.8132, 2),
    ("Rockford", 35.8276, -83.9407, 2),
    ("Elkmont", 35.6537, -83.5804, 2),
    ("Tremont", 35.6209, -83.6774, 2),
    ("Kinzel Springs", 35.6870, -83.7963, 2),
    ("Montvale Springs", 35.6412, -83.9605, 2),
    ("Happy Valley", 35.6090, -83.9574, 2),
    ("Marbledale", 35.9579, -83.8185, 2),
    ("Marble City", 35.9526, -83.9646, 2),
    ("Seven Islands", 35.9481, -83.7038, 2),
    ("Calderwood", 35.5093, -83.9941, 2),
]
FEATURES = [  # name, lat, lon, kind
    ("Tennessee River", 35.9263, -83.9583, "water"),
    ("Holston River", 35.9609, -83.8348, "water"),
    ("French Broad River", 35.9400, -83.7328, "water"),
    ("Little Pigeon River", 35.8772, -83.5764, "water"),
    ("Little River", 35.6660, -83.6750, "water"),
    ("Abrams Creek", 35.6071, -83.9348, "water"),
    ("Little Tennessee River", 35.5450, -83.9950, "water"),
    ("Cades Cove", 35.5911, -83.8529, "region"),
    ("Tuckaleechee Cove", 35.6787, -83.7926, "region"),
    ("Wear Cove", 35.7232, -83.5984, "region"),
    ("Millers Cove", 35.7270, -83.8138, "region"),
    ("Whiteoak Sink", 35.6359, -83.7488, "region"),
    ("Great Smoky Mountains", 35.5760, -83.6400, "region"),
    ("Chilhowee Mountain", 35.7651, -83.7588, "region"),
    ("Bote Mountain", 35.5900, -83.7250, "region"),
    ("The Sugarlands", 35.6670, -83.5188, "region"),
    ("The Great Valley", 35.8950, -83.7300, "region"),
    ("Great Smoky Mountains National Park", 35.6100, -83.6600, "park"),
]

TOURS = [
    dict(id="coves", name="The four windows",
         blurb="Cades Cove and its three sisters — flat limestone floors worn straight through the thrust sheet that carries the mountains.",
         keys=[dict(lat=35.5911, lon=-83.8529, d=7, az=352, el=14,
                    cap="Cades Cove: a level limestone floor inside a wall of conglomerate. Keith mapped the four coves as what they are — holes worn through the Great Smoky thrust, 'produced by erosion of the Wilhite slate and Knox dolomite, while the harder rocks around them were not reduced.' Slide to the geology and the cove shows as a pale island in the grey."),
               dict(lat=35.6359, lon=-83.7488, d=4, az=305, el=17,
                    cap="Whiteoak Sink, on the cove's northeast rim — a blind valley whose creek leaves downward. Keith on the same limestone: in Cades Cove 'scarcely an outcrop appears,' while in the harder rocks around it the streams 'flow over innumerable ledges.'"),
               dict(lat=35.6787, lon=-83.7926, d=6, az=340, el=14,
                    cap="Tuckaleechee Cove, the next window north, with Townsend at its head. The name is Cherokee; the caves under its floor were unknown to the survey and unmapped on the sheet."),
               dict(lat=35.7232, lon=-83.5984, d=7, az=25, el=14,
                    cap="Wear Cove, the third window, under Cove Mountain; the fourth is Millers Cove, at Walland twenty kilometres west. Keith measured the slate that makes them all — 'nothing on the south side of Wears Cove to 800 feet on the south side of Tuckaleeche Cove.'")]),
    dict(id="crest", name="The crest",
         blurb="Twenty miles of state line above five thousand feet, and the grassy balds Keith stopped to define.",
         keys=[dict(lat=35.5686, lon=-83.7063, d=9, az=320, el=15,
                    cap="Thunderhead, 5,525 ft, on the Tennessee–North Carolina line. Keith named a formation for it — the Thunderhead conglomerate, 'a heavy series of conglomerate, graywacke, and sandstone,' the rock that holds up most of this range."),
               dict(lat=35.5636, lon=-83.7328, d=6, az=350, el=14,
                    cap="Spence Field, one of the balds. Keith's definition, printed in 1895: the divides 'are usually smooth and round; many of them have large areas of easy slopes, which are called balds when bare of trees.' Cattle were driven up to this grass every summer."),
               dict(lat=35.5620, lon=-83.5063, d=8, az=282, el=16,
                    cap="Mount Buckley, 6,555 ft — the highest ground the Knoxville sheet holds. Clingmans Dome, 6,644 ft, stands about 120 m further east, just past the neat line; Keith named the Clingman conglomerate for it and sent his reader to the Mount Guyot sheet."),
               dict(lat=35.5207, lon=-83.8655, d=7, az=35, el=15,
                    cap="Gregory Bald, at the range's western end. The whole southeast quarter of this sheet is one grey wash on the geology: a single mass of Ocoee sandstone and conglomerate, age unknown, shoved northwest over the valley limestones.")]),
    dict(id="lumber", name="The lumber road",
         blurb="Keith called the mountain timber virgin forest in May 1895. The Little River Railroad started up the gorge six years later.",
         keys=[dict(lat=35.7281, lon=-83.8132, d=6, az=340, el=14,
                    cap="Walland, where Little River leaves the mountains through a water gap in Chilhowee Mountain. The Little River Lumber Company was chartered in 1901 and laid its railroad up this gap."),
               dict(lat=35.6754, lon=-83.7557, d=7, az=15, el=14,
                    cap="Townsend, named for Col. W. B. Townsend, whose company bought nearly a hundred thousand acres of this timber. In thirty-eight years it built some 150 miles of track and sawed about 560 million board feet."),
               dict(lat=35.6660, lon=-83.6750, d=7, az=300, el=15,
                    cap="The Little River gorge. Keith's last paragraph, written in May 1895: 'the mountain timber has been touched only in the most accessible places, and is for the most part virgin forest.' The railroad reached Elkmont by 1908."),
               dict(lat=35.6209, lon=-83.6774, d=6, az=340, el=15,
                    cap="Tremont, on the Middle Prong — a camp at the end of a spur line. The sawmill closed in 1938, four years after the national park was established around it, and the rails came up the next year.")]),
    dict(id="valley", name="Marble and the Great Valley",
         blurb="Northwest of Chilhowee Mountain the sheet turns to folded limestone, quarry country, and the city at the head of the Tennessee.",
         keys=[dict(lat=35.9606, lon=-83.9207, d=11, az=185, el=14,
                    cap="Knoxville, where the Holston and the French Broad join to make the Tennessee. James White's fort went up here in 1786; on 2 July 1791 William Blount and the Cherokee headmen signed the Treaty of the Holston beside it, and the town laid out that year was named for Henry Knox, the Secretary of War."),
               dict(lat=35.9579, lon=-83.8185, d=6, az=215, el=14,
                    cap="Marbledale, on the belt that made Knoxville the Marble City. Keith: 'Marbles are found in great quantity in the Chickamauga limestone… their chief development is in the belts passing near Knoxville.' The folio's economic sheet marks every quarry."),
               dict(lat=35.8600, lon=-83.7600, d=16, az=228, el=13,
                    cap="The Great Valley of East Tennessee — Cambrian and Ordovician beds folded, faulted and planed off, so that every ridge, every stream and every farm road runs northeast. The reds and pinks on the geology are that grain, one belt of rock at a time."),
               dict(lat=35.7651, lon=-83.7588, d=11, az=300, el=14,
                    cap="Chilhowee Mountain, the long straight wall that cuts the sheet in half. Keith: 'The division northwest of Chilhowee Mountain is part of the Great Valley of East Tennessee; the division southeast of that ridge is part of the mountain belt.'")]),
    dict(id="cherokee", name="Cherokee ground",
         blurb="This is Cherokee homeland — the gaps, the ridges and the drowned river say so, and the sheet was drawn fifty years after the removal.",
         keys=[dict(lat=35.5390, lon=-83.8057, d=5, az=20, el=16,
                    cap="Ekaneetlee Gap — from the Cherokee Egwanulti, 'by the river.' The trace through it crossed the crest from Cades Cove to the Oconaluftee side, and in the Civil War it carried Union men out of North Carolina. Every ridge on this sheet is Cherokee homeland."),
               dict(lat=35.5450, lon=-83.9950, d=7, az=105, el=14,
                    cap="The Little Tennessee, at the sheet's southwest corner. Downstream, just off the map, stood Chilhowee, Tallassee and Chota. In 1838 and 1839 the Cherokee were held in stockades and marched west; those who stayed hidden in these mountains became the Eastern Band, whose Qualla Boundary lies beyond the sheet's southeast corner. The water standing here is Alcoa's — Calderwood Dam, 1930, and Chilhowee Dam, 1957. The 1895 sheet still draws a river."),
               dict(lat=35.5900, lon=-83.7250, d=7, az=340, el=15,
                    cap="Bote Mountain, and the road that follows it. The story the name records is a vote taken by the Cherokee crew who cut the grade: with no v sound in their language, 'vote' came out 'bote,' and the ridge kept the word."),
               dict(lat=35.5911, lon=-83.8529, d=6, az=8, el=14,
                    cap="Cades Cove again, and what came after the folio. John Oliver brought his family in about 1818; by the 1930s the park had bought or condemned some 1,200 landholdings across these mountains, and the cabins, churches and mill still standing in the cove are the ones the Park Service chose to keep.")]),
]
